---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: origin-console-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: origin-console-admin
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: origin-console-admin
    namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: origin-console-admin
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: origin-console-admin
type: kubernetes.io/service-account-token
