apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ENV-eksctl
  region: AWS_REGION
  version: "1.22"

availabilityZones: ["us-east-1a", "us-east-1b","us-east-1c"]

managedNodeGroups:
- name: nodegroup1
  desiredCapacity: 2
  instanceType: t3.medium
  ssh:
    enableSsm: true

secretsEncryption:
  keyARN: MASTER_ARN
