{{- with .Values.cluster.eks -}}
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cluster-eks
  labels:
    argocd.argoproj.io/secret-type: cluster
  annotations:
    managed-by: argocd.argoproj.io
data: {{- omit . "enabled" | toYaml | nindent 2 }} 
{{- end -}}

