apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: example
spec:
  forProvider:
    region: us-east-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    engine: postgres
    engineVersion: '12.9'
    skipFinalSnapshotBeforeDeletion: true
    publiclyAccessible: true
    allocatedStorage: 12
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: example-secret
